#:schema https://json.schemastore.org/any.json

env_files = [".air.env"]
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/template-generator"
  cmd = "go build -o ./tmp/template-generator ."
  delay = 1000
  entrypoint = ["./tmp/template-generator", "-minimized", "-with-logging"]
  exclude_dir = ["bin", "data", "docs", "output", "test", "todo" , "tools"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  ignore_dangerous_root_dir = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[build.windows]
  bin = "tmp\\template-generator.exe"
  cmd = "go build -o ./tmp/template-generator.exe ."
  entrypoint = ["tmp\\template-generator.exe", "-minimized", "-with-logging"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  silent = false
  time = true

[misc]
  clean_on_exit = true
  startup_banner = '''
     _____ _             _   _               _   _ _____          ___  ________        _____           _                    _____                    _       _                  
    /  ___| |           | | (_)             | | | |  _  |         |  \/  |  _  |      /  __ \         | |                  |_   _|                  | |     | |                 
    \ `--.| |_ __ _ _ __| |_ _ _ __   __ _  | |_| | | | |_ __ ___ | .  . | | | | ___  | /  \/_   _ ___| |_ ___  _ __ ___     | | ___ _ __ ___  _ __ | | __ _| |_ ___  ___       
     `--. \ __/ _` | '__| __| | '_ \ / _` | |  _  | | | | '_ ` _ \| |\/| | | | |/ _ \ | |   | | | / __| __/ _ \| '_ ` _ \    | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \/ __|      
    /\__/ / || (_| | |  | |_| | | | | (_| | | | | \ \_/ / | | | | | |  | \ \_/ /  __/ | \__/\ |_| \__ \ || (_) | | | | | |   | |  __/ | | | | | |_) | | (_| | ||  __/\__ \_ _ _ 
    \____/ \__\__,_|_|   \__|_|_| |_|\__, | \_| |_/\___/|_| |_| |_\_|  |_/\___/ \___|  \____/\__,_|___/\__\___/|_| |_| |_|   \_/\___|_| |_| |_| .__/|_|\__,_|\__\___||___(_|_|_)
                                      __/ |                                                                                                   | |                               
                                     |___/                                                                                                    |_|                               
  '''

[proxy]
  enabled = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
