package constants

import "github.com/Tariomka/hommoe_custom_templates/internal/models"

// ContentItemGroup categorizes SidMappings by zone-content kind.
//
//nolint:gochecknoglobals // semantic registry
var ContentItemGroup = struct {
	Mines                     []models.SidMapping
	UtilityStructures         []models.SidMapping
	Treasures                 []models.SidMapping
	UnitRecruitment           []models.SidMapping
	ResourceBanks             []models.SidMapping
	HeroImprovementStructures []models.SidMapping
}{
	Mines: []models.SidMapping{
		ContentIDs.MineWood,
		ContentIDs.MineOre,
		ContentIDs.MineGold,
		IncludeListIDs.RandomRareMines,
		IncludeListIDs.RandomRareMinesBiomeRestricted,
		ContentIDs.MineMercury,
		ContentIDs.MineCrystals,
		ContentIDs.MineGemstones,
		ContentIDs.AlchemyLab,
	},
	UtilityStructures: []models.SidMapping{
		ContentIDs.Watchtower,
		ContentIDs.ManaWell,
		ContentIDs.WindRose,
		ContentIDs.Market,
		ContentIDs.Tavern,
		ContentIDs.Forge,
		ContentIDs.Stables,
		ContentIDs.TearOfTruth,
		ContentIDs.Fountain,
		ContentIDs.Fountain2,
		ContentIDs.BeerFountain,
		ContentIDs.QuixsPath,
		ContentIDs.PileOfBooks,
		ContentIDs.MysteriousStone,
		ContentIDs.CrystalTrail,
		ContentIDs.SacrificialShrine,
		ContentIDs.Chimerologist,
		ContentIDs.EternalDragon,
		ContentIDs.TreeOfAbundance,
		ContentIDs.FlatteringMirror,
		IncludeListIDs.VisionBuildingsTier1,
		IncludeListIDs.VisionBuildingsTier2,
		ContentIDs.InsarasEye,
		ContentIDs.RemoteFoothold,
		ContentIDs.TownGate,
	},
	Treasures: []models.SidMapping{
		ContentIDs.PandoraBox,
		ContentIDs.RandomItemCommon,
		ContentIDs.RandomItemRare,
		ContentIDs.RandomItemEpic,
		ContentIDs.RandomItemLegendary,
		ContentIDs.ScrollBox,
		ContentIDs.EnchantedScrollBox,
		ContentIDs.MythicScrollBox,
		ContentIDs.Prison,
		ContentIDs.Mirage,
		IncludeListIDs.RandomPickupItems,
		IncludeListIDs.MythicScrollBoxPickup,
		IncludeListIDs.PandoraBoxArmyLowTier,
		IncludeListIDs.PandoraBoxArmyHighTier,
	},
	UnitRecruitment: []models.SidMapping{
		// Random hires - matching the player faction.
		IncludeListIDs.RandomHiresLowTier,
		ContentIDs.RandomHire1,
		ContentIDs.RandomHire2,
		ContentIDs.RandomHire3,
		ContentIDs.RandomHire4,
		IncludeListIDs.RandomHiresHighTier,
		ContentIDs.RandomHire5,
		ContentIDs.RandomHire6,
		ContentIDs.RandomHire7,
		IncludeListIDs.RandomHiresAllTier,
		IncludeListIDs.RandomHiresAllTierWeighted,
		ContentIDs.MercenaryGuild,
		// Guarded unit banks.
		IncludeListIDs.RandomGuardedUnitBank,
		ContentIDs.JoustingRange,
		ContentIDs.UnforgottenGrave,
		ContentIDs.PetrifiedMemorial,
		ContentIDs.RitualPyre,
		ContentIDs.BorealCall,
		ContentIDs.TheGorge,
		ContentIDs.PointOfBalance,
	},
	ResourceBanks: []models.SidMapping{
		IncludeListIDs.BasicStorageBanks,
		ContentIDs.StorageWood,
		ContentIDs.StorageOre,
		ContentIDs.StorageGold,
		ContentIDs.StorageMercury,
		ContentIDs.StorageCrystals,
		ContentIDs.StorageGemstones,
		ContentIDs.StorageDust,
		IncludeListIDs.ResourceBanksTier1,
		ContentIDs.Gardener,
		ContentIDs.Windmill,
		ContentIDs.Village,
		ContentIDs.GingerbreadHouse,
		ContentIDs.PeasantCart,
		ContentIDs.AbandonedCorpse,
		ContentIDs.CrowNest,
		ContentIDs.GoblinCache,
		IncludeListIDs.ResourceBanksTier2,
		ContentIDs.MontyHall,
		ContentIDs.HerosCrypt,
		IncludeListIDs.GuardedBanksTier1,
		ContentIDs.BlackTower,
		ContentIDs.AbandonedMansion,
		ContentIDs.MereasShrine,
		ContentIDs.ShadyDen,
		IncludeListIDs.GuardedBanksTier2,
		ContentIDs.RaidersCamp,
		ContentIDs.OvergrownGrave,
		ContentIDs.LegionsMemorial,
		ContentIDs.AlvarsEye,
		ContentIDs.CursedOldHouse,
		ContentIDs.AbnormalStructure,
		ContentIDs.PrismaticLair,
		ContentIDs.UncannyRite,
		ContentIDs.CircleOfLife,
		ContentIDs.IridescentAbbey,
		IncludeListIDs.GuardedBanksTier3,
		ContentIDs.TroglodyteThrone,
		ContentIDs.TwilightBloom,
		ContentIDs.UnstableRuins,
		ContentIDs.DragonUtopia,
		ContentIDs.ResearchLaboratory,
		IncludeListIDs.UtopiaBuildings,
		IncludeListIDs.EpicGuardedResourceBanks,
		IncludeListIDs.GuardedUnitBanksBiomeRestricted,
		IncludeListIDs.GuardedUnitBanksNoBiome,
	},
	HeroImprovementStructures: []models.SidMapping{
		IncludeListIDs.HeroBuffTier1,
		IncludeListIDs.HeroImprovementUncommon,
		IncludeListIDs.HeroStatsAndSkillsTier1,
		ContentIDs.StingingSword,
		ContentIDs.ArmoryAutomaton,
		ContentIDs.MagicWheel,
		ContentIDs.KnowledgeGarden,
		ContentIDs.WiseOwl,
		IncludeListIDs.HeroStatsAndSkillsTier2,
		ContentIDs.Fort,
		ContentIDs.OrbObservatory,
		ContentIDs.University,
		ContentIDs.Circus,
		ContentIDs.InfernalCirque,
		IncludeListIDs.HeroStatsAndSkillsTier3,
		ContentIDs.Maze,
		ContentIDs.TrialScales,
		ContentIDs.CollegeOfWonder,
		ContentIDs.LearningStone,
		IncludeListIDs.HeroExpTier2,
		ContentIDs.LostLibrary,
		ContentIDs.TreeOfKnowledge,
		IncludeListIDs.MagicBuildingsTier1,
		ContentIDs.MysticalTower,
		ContentIDs.CelestialSphere,
		ContentIDs.AltarOfMagic1,
		ContentIDs.AltarOfMagic2,
		ContentIDs.AltarOfMagic3,
		ContentIDs.AltarOfMagic4,
		IncludeListIDs.MagicBuildingsTier2,
		ContentIDs.MagicAmplifier1,
		ContentIDs.MagicAmplifier2,
		ContentIDs.MagicAmplifier3,
		ContentIDs.MagicAmplifier4,
		ContentIDs.HuntsmansCamp,
		ContentIDs.FickleShrine,
		ContentIDs.Arena,
	},
}
