package registry

type objectInteractables struct {
	interactableMines
	interactableStorages
	AlchemyLab string
}

var objectInteractableValues = objectInteractables{
	interactableMines:    interactableMineValues,
	interactableStorages: interactableStorageValues,
	AlchemyLab:           "alchemy_lab",
}

func GetMapObjectInteractableValues() objectInteractables {
	return objectInteractableValues
}

type interactableMines struct {
	GoldMine     string
	WoodMine     string
	OreMine      string
	CrystalMine  string
	MercuryMine  string
	GemstoneMine string
}

var interactableMineValues = interactableMines{
	GoldMine:     "mine_gold",
	WoodMine:     "mine_wood",
	OreMine:      "mine_ore",
	CrystalMine:  "mine_crystals",
	MercuryMine:  "mine_mercury",
	GemstoneMine: "mine_gemstones",
}

type interactableStorages struct {
	WoodStorage     string
	OreStorage      string
	GoldStorage     string
	CrystalStorage  string
	MercuryStorage  string
	GemstoneStorage string
	DustStorage     string
}

var interactableStorageValues = interactableStorages{
	WoodStorage:     "storage_wood",
	OreStorage:      "storage_ore",
	GoldStorage:     "storage_gold",
	CrystalStorage:  "storage_crystals",
	MercuryStorage:  "storage_mercury",
	GemstoneStorage: "storage_gemstones",
	DustStorage:     "storage_dust",
}

// "id": "custom_storage_ore",
// "id": "custom_storage_gold",
// "id": "custom_storage_gemstones",
// "id": "custom_storage_crystals",
// "id": "custom_storage_mercury",
// "id": "custom_storage_dust",

// "id": "gardener",

// "id": "custom_gardener",

// "id": "windmill",
// "id": "custom_windmill",

// "id": "shady_den",

// "id": "custom_shady_den",

// "id": "village",
// "id": "custom_village",

// "id": "gingerbread_house",
// "id": "custom_gingerbread_house",

// "id": "stinging_sword",
// "id": "armory_automaton",
// "id": "magic_wheel",
// "id": "knowledge_garden",
// "id": "maze",
// "id": "trial_scales",
// "id": "fort",
// "id": "orb_observatory",
// "id": "college_of_wonder",
// "id": "flattering_mirror",
// "id": "beer_fountain",
// "id": "mysterious_stone",
// "id": "crystal_trail",
// "id": "altar_of_magic_1",
// "id": "custom_altar_of_magic_1",
// "id": "altar_of_magic_2",
// "id": "custom_altar_of_magic_2",
// "id": "altar_of_magic_3",
// "id": "custom_altar_of_magic_3",
// "id": "altar_of_magic_4",
// "id": "custom_altar_of_magic_4",
// "id": "magic_amplifier_1",
// "id": "magic_amplifier_2",
// "id": "magic_amplifier_3",
// "id": "magic_amplifier_4",
// "id": "tree_of_knowledge",
// "id": "huntsmans_camp",
// "id": "temporary_camp",
// "id": "wise_owl",
// "id": "custom_wise_owl",
// "id": "university",
// "id": "custom_university",
// "id": "circus",
// "id": "watchtower",
// "id": "wind_rose",
// "id": "stables",
// "id": "fountain",
// "id": "fountain_2",

// "id": "quixs_path",
// "id": "learning_stone",
// "id": "lost_library",
// "id": "pile_of_books",
// "id": "mereas_shrine",
// "id": "fickle_shrine",
// "id": "town_gate",
// "id": "portal_1",
// "id": "portal_1_2",
// "id": "portal_1_3",
// "id": "portal_2",
// "id": "portal_2_2",
// "id": "portal_2_3",
// "id": "portal_3",
// "id": "portal_3_2",
// "id": "portal_3_3",
// "id": "portal_4",
// "id": "portal_4_2",
// "id": "portal_4_3",
// "id": "portal_5",
// "id": "portal_5_2",
// "id": "portal_5_3",
// "id": "portal_magic",
// "id": "market",
// "id": "forge",
// "id": "sacrificial_shrine",
// "id": "chimerologist",
// "id": "celestial_sphere",
// "id": "mystical_tower",
// "id": "tavern",
// "id": "insaras_eye",
// "id": "prison",
// "id": "mana_well",
// "id": "tear_of_truth",
// "id": "arena",
// "id": "goblin_cache",
// "id": "custom_goblin_cache",
// "id": "peasant_cart",

// "id": "custom_peasant_cart",
// "id": "abandoned_corpse",
// "id": "custom_abandoned_corpse",
// "id": "crow_nest",
// "id": "custom_crow_nest",
// "id": "monty_hall",
// "id": "custom_monty_hall",
// "id": "heros_crypt",
// "id": "custom_heros_crypt",
// "id": "raiders_camp",
// "id": "custom_raiders_camp",
// "id": "overgrown_grave",
// "id": "custom_overgrown_grave",
// "id": "legions_memorial",
// "id": "custom_legions_memorial",
// "id": "prismatic_lair",
// "id": "custom_prismatic_lair",
// "id": "uncanny_rite",
// "id": "custom_uncanny_rite",
// "id": "circle_of_life",
// "id": "custom_circle_of_life",
// "id": "iridescent_abbey",
// "id": "custom_iridescent_abbey",
// "id": "troglodyte_throne",
// "id": "custom_troglodyte_throne",
// "id": "unstable_ruins",
// "id": "custom_unstable_ruins",
// "id": "abnormal_structure",
// "id": "custom_abnormal_structure",
// "id": "testing_grounds",
// "id": "custom_testing_grounds",
// "id": "twilight_bloom",
// "id": "custom_twilight_bloom",
// "id": "dragon_utopia",
// "id": "custom_dragon_utopia",
// "id": "research_laboratory",
// "id": "custom_research_laboratory",
// "id": "underground_lair",
// "id": "custom_underground_lair",
// "id": "black_tower",
// "id": "custom_black_tower",
// "id": "abandoned_mansion",
// "id": "custom_abandoned_mansion",
// "id": "tree_of_abundance",
// "id": "alvars_eye",
// "id": "custom_alvars_eye",
// "id": "cursed_old_house",
// "id": "custom_cursed_old_house",
// "id": "eternal_dragon",
// "id": "infernal_cirque",
// "id": "mirage",
// "id": "mercenary_guild",
// "id": "point_of_balance",
// "id": "custom_point_of_balance",
// "id": "jousting_range",
// "id": "custom_jousting_range",
// "id": "vanguard",
// "id": "custom_vanguard",
// "id": "ritual_pyre",
// "id": "custom_ritual_pyre",
// "id": "unforgotten_grave",
// "id": "custom_unforgotten_grave",
// "id": "boreal_call",
// "id": "custom_boreal_call",
// "id": "the_gorge",
// "id": "custom_the_gorge",
// "id": "petrified_memorial",
// "id": "custom_petrified_memorial",
// "id": "remote_foothold",
// "id": "pocket_dimension",
// "id": "abandoned_outpost",
// "id": "human_city",
// "id": "undead_city",
// "id": "dungeon_city",
// "id": "nature_city",
// "id": "unfrozen_city",
// "id": "demon_city",
// "id": "barracks_neutral_dragon_lich",
// "id": "barracks_human_1",
// "id": "barracks_human_2",
// "id": "barracks_human_3",
// "id": "barracks_human_4",
// "id": "barracks_human_5",
// "id": "barracks_human_6",
// "id": "barracks_human_7",
// "id": "barracks_necropolis_1",
// "id": "barracks_necropolis_2",
// "id": "barracks_necropolis_3",
// "id": "barracks_necropolis_4",
// "id": "barracks_necropolis_5",
// "id": "barracks_necropolis_6",
// "id": "barracks_necropolis_7",
// "id": "barracks_nature_1",
// "id": "barracks_nature_2",
// "id": "barracks_nature_3",
// "id": "barracks_nature_4",
// "id": "barracks_nature_5",
// "id": "barracks_nature_6",
// "id": "barracks_nature_7",
// "id": "barracks_dungeon_1",
// "id": "barracks_dungeon_2",
// "id": "barracks_dungeon_3",
// "id": "barracks_dungeon_4",
// "id": "barracks_dungeon_5",
// "id": "barracks_dungeon_6",
// "id": "barracks_dungeon_7",
// "id": "barracks_unfrozen_1",
// "id": "barracks_unfrozen_2",
// "id": "barracks_unfrozen_3",
// "id": "barracks_unfrozen_4",
// "id": "barracks_unfrozen_5",
// "id": "barracks_unfrozen_6",
// "id": "barracks_unfrozen_7",
// "id": "barracks_demon_1",
// "id": "barracks_demon_2",
// "id": "barracks_demon_3",
// "id": "barracks_demon_4",
// "id": "barracks_demon_5",
// "id": "barracks_demon_6",
// "id": "barracks_demon_7",
// "id": "pvp_promo_barracks",
// "id": "pvp_promo_barracks_necropolis",
// "id": "barracks_neutral_1",
// "id": "barracks_neutral_2",
// "id": "barracks_neutral_3",
// "id": "barracks_neutral_4",
// "id": "barracks_neutral_5",
// "id": "barracks_neutral_6",
// "id": "barracks_neutral_7",
// "id": "barracks_neutral_8",
// "id": "barracks_neutral_9",
// "id": "barracks_neutral_10",
// "id": "barracks_neutral_11",
// "id": "barracks_neutral_12",
// "id": "barracks_neutral_13",
// "id": "barracks_neutral_14",
// "id": "barracks_neutral_15",
// "id": "barracks_neutral_16",
// "id": "barracks_neutral_17",
// "id": "unit_trade_lab_kitten_horn",
// "id": "unit_trade_lab_gnat",
// "id": "block",
// "id": "shroom_of_growth",
// "id": "fairy_ring",
// "id": "learning_stone_old",
// "id": "gladiator_arena",

type interactableCustomStorages struct {
	CustomWoodStorage     string
	CustomOreStorage      string
	CustomGoldStorage     string
	CustomCrystalStorage  string
	CustomMercuryStorage  string
	CustomGemstoneStorage string
	CustomDustStorage     string
}

var interactableCustomStorageValues = interactableCustomStorages{
	CustomWoodStorage:     "custom_storage_wood",
	CustomOreStorage:      "custom_storage_ore",
	CustomGoldStorage:     "custom_storage_gold",
	CustomCrystalStorage:  "custom_storage_crystals",
	CustomMercuryStorage:  "custom_storage_mercury",
	CustomGemstoneStorage: "custom_storage_gemstones",
	CustomDustStorage:     "custom_storage_dust",
}

// "id": "stinging_sword_campaign",
// "id": "armory_automaton_campaign",
// "id": "magic_wheel_campaign",
// "id": "knowledge_garden_campaign",
// "id": "maze_campaign",
// "id": "fort_campaign",
// "id": "orb_observatory_campaign",
// "id": "college_of_wonder_campaign",
// "id": "goblin_cache_campaign",
// "id": "peasant_cart_campaign",
// "id": "crow_nest_campaign",
// "id": "shady_den_campaign",

// "id": "block_campaign_tree_grass",
// "id": "block_campaign_tree_autumn",
// "id": "block_campaign_tree_dirt",
// "id": "block_campaign_tree_dead",
// "id": "block_campaign_tree_withered",
// "id": "block_campaign_tree_snow",
// "id": "block_campaign_mountain_dirt",
// "id": "block_campaign",

// "id": "campaign_stinging_sword",
// "id": "campaign_armory_automaton",
// "id": "campaign_magic_wheel",
// "id": "campaign_knowledge_garden",
// "id": "campaign_college_of_wonder",
// "id": "campaign_fort",
// "id": "campaign_orb_observatory",
// "id": "campaign_maze",
// "id": "campaign_trial_scales",
// "id": "campaign_shady_den",
// "id": "campaign_flattering_mirror",
// "id": "campaign_gingerbread_house",
// "id": "campaign_lost_library_empty",
// "id": "campaign_M1_broken_bridge",
// "id": "campaign_M2_shroom_tether",
// "id": "campaign_M2_rockfall_1",
// "id": "campaign_M2_rockfall_2",
// "id": "campaign_M2_empty_mine",
// "id": "campaign_M3_necro_altar",
// "id": "campaign_M3_cage",
// "id": "campaign_M4_burning_man",
// "id": "campaign_M4_construction_site",
// "id": "campaign_M4_diary",
// "id": "campaign_M4_stargazer_tower",
// "id": "campaign_M5_death_knight_house_empty",
// "id": "campaign_M5_death_knight_house",
// "id": "campaign_M6_mearea_shrine",
// "id": "campaign_M6_cage",
// "id": "campaign_M9_scientist_house",
// "id": "campaign_M9_necromancy_amplifier",
// "id": "campaign_M9_necromancy_amplifier_foundation",
// "id": "campaign_M9_necromancy_amplifier_destroyed",
// "id": "campaign_M9_block_angel1",
// "id": "campaign_M9_block_angel2",
// "id": "campaign_M9_block_angel3",
// "id": "campaign_M9_block_angel4",
// "id": "campaign_M9_sylvan_altar",
// "id": "campaign_M9_phoenix_nest_shroom",
// "id": "campaign_M9_phoenix_nest",
// "id": "campaign_M9_phoenix_egg",
// "id": "campaign_M9_tomb",
