package test_helpers

import (
	"github.com/Tariomka/hommoe_custom_templates/internal/models/template"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/template/template_inner/common"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/template/template_inner/content"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/template/template_inner/game_rules"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/template/template_inner/variant"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/template/template_inner/zone_layout"
)

func intPtr(i int) *int { return &i }

func GetDefaultTemplate() template.RmgTemplateModel {
	return template.RmgTemplateModel{
		Name:                "Custom Template",
		GameMode:            "Classic",
		Description:         "Generated with Custom Template Editor: Balanced layout, no neutral zones, 1 castle per player zone.",
		DisplayWinCondition: "win_condition_1",
		SizeX:               160,
		SizeZ:               160,
		ValueOverrides:      nil,
		Orientation:         nil,
		Border:              nil,
		GameRules: template.GameRules{
			HeroCountMin:       4,
			HeroCountMax:       8,
			HeroCountIncrement: 1,
			HeroHireBan:        false,
			EncounterHoles:     false,
			TournamentRules:    false,
			Bonuses: game_rules.BonusList{{
				SID:            "add_bonus_hero_stat",
				ReceiverSide:   -1,
				ReceiverFilter: "all_heroes",
				Parameters:     []string{"movementBonus", "0"},
			}},
			WinConditions: template.WinConditions{
				Classic:                              true,
				Desertion:                            true,
				DesertionDay:                         3,
				DesertionValue:                       3000,
				HeroLighting:                         true,
				HeroLightingDay:                      1,
				LostStartCity:                        false,
				LostStartCityDay:                     3,
				LostStartHero:                        false,
				CityHold:                             false,
				CityHoldDays:                         6,
				GladiatorArena:                       false,
				GladiatorArenaRegistrationStartWork:  false,
				GladiatorArenaRegistrationStartFight: false,
				GladiatorArenaDaysDelayStart:         0,
				GladiatorArenaCountDay:               0,
				ChampionSelectRule:                   "",
				Tournament:                           false,
				TournamentPointsToWin:                0,
				TournamentSaveArmy:                   false,
				TournamentDays:                       nil,
				TournamentAnnounceDays:               nil,
			},
			GladiatorArena:                       false,
			GladiatorArenaRegistrationStartWork:  false,
			GladiatorArenaRegistrationStartFight: false,
			GladiatorArenaDaysDelayStart:         0,
			GladiatorArenaCountDay:               0,
			ChampionSelectRule:                   "",
			GlobalBans:                           nil,
			FactionLawsExpModifier:               1,
			AstrologyExpModifier:                 1,
		},
		GlobalBans: nil,
		Variants: []template.Variant{{
			Orientation: variant.Orientation{
				Mode:                 "",
				ZeroAngleZone:        "Spawn-B",
				BaseAngleMin:         45,
				BaseAngleMax:         45,
				RandomAngleAmplitude: 360,
				RandomAngleStep:      180,
			},
			Border: variant.Border{
				CornerRadius:   0,
				ObstaclesWidth: 3,
				ObstaclesNoise: []variant.Noise{{Amplitude: 1, Frequency: 12}},
				WaterWidth:     0,
				WaterNoise:     []variant.Noise{{Amplitude: 1, Frequency: 12}},
				WaterType:      "water grass",
			},
			Zones: []template.Zone{
				{
					Name:                                "Spawn-B",
					GeneratorPosition:                   &[2]float64{0.8799878400648531, 0.4969600324265629}, // Most likely this is random
					GeneratorRing:                       intPtr(0),
					Size:                                1,
					Layout:                              "zone_layout_spawns",
					GuardCutoffValue:                    2_000,
					GuardRandomization:                  0.05,
					GuardMultiplier:                     1,
					GuardWeeklyIncrement:                0.2,
					GuardReactionDistribution:           []int{60, 20, 10, 10, 2, 0},
					DiplomacyModifier:                   -0.5,
					EncounterHolesSettings:              nil,
					RandomHireEnableWeeklyUnitIncrement: nil,
					RandomHireInitialUnitIncrement:      nil,
					GuardedContentPool: []string{
						"classic_template_pool_random_t2_item",
						"classic_template_pool_random_t2_pandora",
						"classic_template_pool_random_t2_hire",
						"classic_template_pool_random_t2_unit_bank",
						"classic_template_pool_random_t2_res_bank",
						"classic_template_pool_random_t2_stat",
						"classic_template_pool_random_t2_magic",
					},
					UnguardedContentPool: []string{
						"classic_template_pool_random_unguarded_t2_item",
						"classic_template_pool_random_unguarded_t2_pandora",
						"classic_template_pool_random_unguarded_t2_hire",
						"classic_template_pool_random_unguarded_t2_unit_bank",
						"classic_template_pool_random_unguarded_t2_res_bank",
						"classic_template_pool_random_unguarded_t2_stat",
						"classic_template_pool_random_unguarded_t2_magic",
					},
					ResourcesContentPool: []string{"content_pool_general_resources_start_zone_poor"},
					MandatoryContent:     variant.StringList{"mandatory_content_side_B"},
					ContentCountLimits: variant.StringList{
						"content_limits_side_1_2",
						"content_limits_side_1_3",
						"content_limits_side_1_4",
						"content_limits_side_1_5",
						"content_limits_side_1_6",
						"content_limits_side_2_3",
						"content_limits_side_2_4",
						"content_limits_side_2_5",
						"content_limits_side_2_6",
						"content_limits_side_3_4",
						"content_limits_side_3_5",
						"content_limits_side_3_6",
						"content_limits_side_4_5",
						"content_limits_side_4_6",
						"content_limits_side_5_6",
					},
					GuardedContentValue:          282_842,
					GuardedContentValuePerArea:   2_378,
					UnguardedContentValue:        70_710,
					UnguardedContentValuePerArea: 475,
					ResourcesValue:               56_568,
					ResourcesValuePerArea:        356,
					MainObjects: []template.MainObject{{
						Type:                      "Spawn",
						Spawn:                     "Player1",
						Owner:                     "",
						RemoveGuardIfHasOwner:     true,
						GuardChance:               1,
						GuardValue:                5_000,
						GuardRandomization:        0,
						GuardWeeklyIncrement:      0.1,
						BuildingsConstructionSid:  "default_buildings_construction",
						Faction:                   nil,
						Factions:                  nil,
						Placement:                 "Uniform",
						PlacementArgs:             []string{"true", "0.7", "0"},
						HoldCityWinCon:            false,
						IsKeyObject:               false,
						EnableWeeklyUnitIncrement: false,
						InitialUnitIncrement:      0,
					}},
					ZoneBiome:          variant.TypedRef{Type: "MatchMainObject", Args: []string{"0"}},
					ContentBiome:       variant.TypedRef{Type: "MatchMainObject", Args: []string{"0"}},
					MetaObjectsBiome:   variant.TypedRef{Type: "MatchMainObject", Args: []string{"0"}},
					CrossroadsPosition: intPtr(0),
					Roads: []variant.Road{
						{
							Type:                 "",
							From:                 variant.TypedRef{Type: "MainObject", Args: []string{"0"}},
							To:                   variant.TypedRef{Type: "MandatoryContent", Args: []string{"name_remote_foothold_1"}},
							Road:                 nil,
							SimTurnSquad:         false,
							GuardValue:           0,
							GuardWeeklyIncrement: 0,
						},
						{
							Type:                 "",
							From:                 variant.TypedRef{Type: "MainObject", Args: []string{"0"}},
							To:                   variant.TypedRef{Type: "Connection", Args: []string{"Rnd-B-A"}},
							Road:                 nil,
							SimTurnSquad:         false,
							GuardValue:           0,
							GuardWeeklyIncrement: 0,
						},
					},
				},
				{
					Name:                                "Spawn-A",
					GeneratorPosition:                   &[2]float64{0.12, 0.5},
					GeneratorRing:                       intPtr(0),
					Size:                                1,
					Layout:                              "zone_layout_spawns",
					GuardCutoffValue:                    2_000,
					GuardRandomization:                  0.05,
					GuardMultiplier:                     1,
					GuardWeeklyIncrement:                0.2,
					GuardReactionDistribution:           []int{60, 20, 10, 10, 2, 0},
					DiplomacyModifier:                   -0.5,
					EncounterHolesSettings:              nil,
					RandomHireEnableWeeklyUnitIncrement: nil,
					RandomHireInitialUnitIncrement:      nil,
					GuardedContentPool: []string{
						"classic_template_pool_random_t2_item",
						"classic_template_pool_random_t2_pandora",
						"classic_template_pool_random_t2_hire",
						"classic_template_pool_random_t2_unit_bank",
						"classic_template_pool_random_t2_res_bank",
						"classic_template_pool_random_t2_stat",
						"classic_template_pool_random_t2_magic",
					},
					UnguardedContentPool: []string{
						"classic_template_pool_random_unguarded_t2_item",
						"classic_template_pool_random_unguarded_t2_pandora",
						"classic_template_pool_random_unguarded_t2_hire",
						"classic_template_pool_random_unguarded_t2_unit_bank",
						"classic_template_pool_random_unguarded_t2_res_bank",
						"classic_template_pool_random_unguarded_t2_stat",
						"classic_template_pool_random_unguarded_t2_magic",
					},
					ResourcesContentPool: []string{"content_pool_general_resources_start_zone_poor"},
					MandatoryContent:     variant.StringList{"mandatory_content_side_A"},
					ContentCountLimits: variant.StringList{
						"content_limits_side_1_2",
						"content_limits_side_1_3",
						"content_limits_side_1_4",
						"content_limits_side_1_5",
						"content_limits_side_1_6",
						"content_limits_side_2_3",
						"content_limits_side_2_4",
						"content_limits_side_2_5",
						"content_limits_side_2_6",
						"content_limits_side_3_4",
						"content_limits_side_3_5",
						"content_limits_side_3_6",
						"content_limits_side_4_5",
						"content_limits_side_4_6",
						"content_limits_side_5_6",
					},
					GuardedContentValue:          282_842,
					GuardedContentValuePerArea:   2_378,
					UnguardedContentValue:        70_710,
					UnguardedContentValuePerArea: 475,
					ResourcesValue:               56_568,
					ResourcesValuePerArea:        356,
					MainObjects: []template.MainObject{{
						Type:                      "Spawn",
						Spawn:                     "Player2",
						Owner:                     "",
						RemoveGuardIfHasOwner:     true,
						GuardChance:               1,
						GuardValue:                5_000,
						GuardRandomization:        0,
						GuardWeeklyIncrement:      0.1,
						BuildingsConstructionSid:  "default_buildings_construction",
						Faction:                   nil,
						Factions:                  nil,
						Placement:                 "Uniform",
						PlacementArgs:             []string{"true", "0.7", "0"},
						HoldCityWinCon:            false,
						IsKeyObject:               false,
						EnableWeeklyUnitIncrement: false,
						InitialUnitIncrement:      0,
					}},
					ZoneBiome:          variant.TypedRef{Type: "MatchMainObject", Args: []string{"0"}},
					ContentBiome:       variant.TypedRef{Type: "MatchMainObject", Args: []string{"0"}},
					MetaObjectsBiome:   variant.TypedRef{Type: "MatchMainObject", Args: []string{"0"}},
					CrossroadsPosition: intPtr(0),
					Roads: []variant.Road{
						{
							Type:                 "",
							From:                 variant.TypedRef{Type: "MainObject", Args: []string{"0"}},
							To:                   variant.TypedRef{Type: "MandatoryContent", Args: []string{"name_remote_foothold_1"}},
							Road:                 nil,
							SimTurnSquad:         false,
							GuardValue:           0,
							GuardWeeklyIncrement: 0,
						},
						{
							Type:                 "",
							From:                 variant.TypedRef{Type: "MainObject", Args: []string{"0"}},
							To:                   variant.TypedRef{Type: "Connection", Args: []string{"Rnd-B-A"}},
							Road:                 nil,
							SimTurnSquad:         false,
							GuardValue:           0,
							GuardWeeklyIncrement: 0,
						},
					},
				},
			},
			Connections: nil,
		}},
		ZoneLayouts: []template.ZoneLayoutDef{
			{
				Name:                  "zone_layout_spawns",
				ObstaclesFill:         0.24,
				ObstaclesFillVoid:     0.48,
				LakesFill:             0.3,
				MinLakeArea:           16,
				ElevationClusterScale: 0.16,
				ElevationModes: []zone_layout.ElevationMode{
					{Weight: 2, MinElevatedFraction: 0.2, MaxElevatedFraction: 0.4},
					{Weight: 1, MinElevatedFraction: 0.6, MaxElevatedFraction: 0.8},
				},
				RoadClusterArea: 160,
				GuardedEncounterResourceFractions: zone_layout.GuardedEncounterResourceFractions{
					CountBounds: []int{},
					Fractions:   []float64{0.66},
				},
				AmbientPickupDistribution: zone_layout.AmbientPickupDistribution{
					Repulsion:          1,
					Noise:              0.4,
					RoadAttraction:     -0.3,
					ObstacleAttraction: 0,
					GroupSizeWeights:   []int{20, 2, 1},
				},
			},
			{
				Name:                  "zone_layout_sides",
				ObstaclesFill:         0.36,
				ObstaclesFillVoid:     0.5,
				LakesFill:             0.25,
				MinLakeArea:           16,
				ElevationClusterScale: 0.128,
				ElevationModes: []zone_layout.ElevationMode{
					{Weight: 2, MinElevatedFraction: 0.2, MaxElevatedFraction: 0.4},
					{Weight: 1, MinElevatedFraction: 0.6, MaxElevatedFraction: 0.8},
				},
				RoadClusterArea: 128,
				GuardedEncounterResourceFractions: zone_layout.GuardedEncounterResourceFractions{
					CountBounds: []int{},
					Fractions:   []float64{0.66},
				},
				AmbientPickupDistribution: zone_layout.AmbientPickupDistribution{
					Repulsion:          1,
					Noise:              0.3,
					RoadAttraction:     -0.3,
					ObstacleAttraction: 0,
					GroupSizeWeights:   []int{20, 2, 1},
				},
			},
			{
				Name:                  "zone_layout_treasure_zone",
				ObstaclesFill:         0.5,
				ObstaclesFillVoid:     0.5,
				LakesFill:             0.45,
				MinLakeArea:           12,
				ElevationClusterScale: 0.12,
				ElevationModes: []zone_layout.ElevationMode{
					{Weight: 2, MinElevatedFraction: 0.2, MaxElevatedFraction: 0.4},
					{Weight: 1, MinElevatedFraction: 0.6, MaxElevatedFraction: 0.8},
				},
				RoadClusterArea: 96,
				GuardedEncounterResourceFractions: zone_layout.GuardedEncounterResourceFractions{
					CountBounds: []int{},
					Fractions:   []float64{0.66},
				},
				AmbientPickupDistribution: zone_layout.AmbientPickupDistribution{
					Repulsion:          1,
					Noise:              0.3,
					RoadAttraction:     -0.3,
					ObstacleAttraction: 0,
					GroupSizeWeights:   []int{12, 3, 1},
				},
			},
			{
				Name:                  "zone_layout_center",
				ObstaclesFill:         0.56,
				ObstaclesFillVoid:     0.6,
				LakesFill:             0.3,
				MinLakeArea:           10,
				ElevationClusterScale: 0.128,
				ElevationModes: []zone_layout.ElevationMode{
					{Weight: 2, MinElevatedFraction: 0.2, MaxElevatedFraction: 0.4},
					{Weight: 1, MinElevatedFraction: 0.6, MaxElevatedFraction: 0.8},
				},
				RoadClusterArea: 96,
				GuardedEncounterResourceFractions: zone_layout.GuardedEncounterResourceFractions{
					CountBounds: []int{},
					Fractions:   []float64{0.66},
				},
				AmbientPickupDistribution: zone_layout.AmbientPickupDistribution{
					Repulsion:          1,
					Noise:              0.3,
					RoadAttraction:     -0.25,
					ObstacleAttraction: 0,
					GroupSizeWeights:   []int{12, 4, 1},
				},
			},
		},
		MandatoryContent: []template.MandatoryContent{
			{
				Name: "mandatory_content_side_A",
				Content: []content.MandatoryContentItem{{
					SID:       "remote_foothold",
					Name:      "name_remote_foothold_1",
					IsMine:    false,
					IsGuarded: false,
					Rules: []common.PlacementRule{
						{
							Type:      "Crossroads",
							Args:      nil,
							TargetMin: 0.2,
							TargetMax: 0.3,
							Target:    0,
							Weight:    0,
						},
						{
							Type:      "MainObject",
							Args:      []any{"0"},
							TargetMin: 0.2,
							TargetMax: 0.4,
							Target:    0,
							Weight:    0,
						},
					},
					Variant:             nil,
					Owner:               "",
					GuardValue:          0,
					IncludeLists:        nil,
					Content:             nil,
					DesignatedEncounter: nil,
					SoloEncounter:       true,
					Road:                nil,
				}},
			},
			{
				Name: "mandatory_content_side_B",
				Content: []content.MandatoryContentItem{{
					SID:       "remote_foothold",
					Name:      "name_remote_foothold_1",
					IsMine:    false,
					IsGuarded: false,
					Rules: []common.PlacementRule{
						{
							Type:      "Crossroads",
							Args:      nil,
							TargetMin: 0.2,
							TargetMax: 0.3,
							Target:    0,
							Weight:    0,
						},
						{
							Type:      "MainObject",
							Args:      []any{"0"},
							TargetMin: 0.2,
							TargetMax: 0.4,
							Target:    0,
							Weight:    0,
						},
					},
					Variant:             nil,
					Owner:               "",
					GuardValue:          0,
					IncludeLists:        nil,
					Content:             nil,
					DesignatedEncounter: nil,
					SoloEncounter:       true,
					Road:                nil,
				}},
			},
		},
		ContentCountLimits: []template.ContentCountLimit{
			{
				Name: "content_limits_side",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_0_0",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_1_2",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_1_3",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_1_4",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_1_5",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_1_6",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_2_3",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_2_4",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_2_5",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_2_6",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_3_4",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_3_5",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_3_6",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_4_5",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_4_6",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
			{
				Name: "content_limits_side_5_6",
				Limits: []content.ContentLimit{
					{SID: "black_tower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 0},
					{SID: "fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fountain_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "mana_well", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "beer_fountain", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "market", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "forge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "stables", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "watchtower", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wind_rose", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "quixs_path", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "crystal_trail", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "mysterious_stone", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "university", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "wise_owl", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "celestial_sphere", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "pile_of_books", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "insaras_eye", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "tear_of_truth", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "tree_of_abundance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "huntsmans_camp", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "shady_den", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "random_hire_1", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_2", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_3", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_4", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_5", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_6", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "random_hire_7", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 6},
					{SID: "arena", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "sacrificial_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "chimerologist", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "circus", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "infernal_cirque", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "flattering_mirror", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 2},
					{SID: "fickle_shrine", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "point_of_balance", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "pandora_box", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 4},
					{SID: "ritual_pyre", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "boreal_call", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 3},
					{SID: "jousting_range", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "unforgotten_grave", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "petrified_memorial", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
					{SID: "the_gorge", IncludeLists: nil, Content: nil, Variant: nil, MaxCount: 1},
				},
			},
		},
		ContentPools: []template.ContentPool{},
		ContentLists: []template.ContentList{},
	}
}
