package preview_service

import (
	"strings"

	"github.com/Tariomka/hommoe_custom_templates/internal/entities"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/preview"
)

// ExtractZoneLetter returns the trailing letter portion of a zone name like
// "Spawn-A" → "A" or "Neutral-C" → "C". Plain names (e.g. "Hub") pass through.
func ExtractZoneLetter(zoneName string) string {
	if after, ok := strings.CutPrefix(zoneName, "Spawn-"); ok {
		return after
	}

	if after, ok := strings.CutPrefix(zoneName, "Neutral-"); ok {
		return after
	}

	return zoneName
}

// ClassifyZoneTier guesses a neutral zone's tier from its content pools,
// layout name, and zone name (in order of reliability).
func ClassifyZoneTier(zone entities.Zone) preview.ZoneTier {
	if strings.HasPrefix(zone.Name, "Spawn-") {
		return preview.TierPlastic
	}
	// Platinum (the Highest/hub profile) shares its t5 pool markers with gold
	// zones; the rich-treasure resources pool is what sets it apart.
	if isPlatinumZone(zone) {
		return preview.TierPlatinum
	}
	// Most reliable for templates generated by this tool: the guarded content
	// pool names embed the encounter tier (t1/t2/t3/t4/t5). High-tier zones
	// share the "treasure" layout with medium-tier ones, so layout alone cannot
	// distinguish them.
	if tier, found := tierFromContentPools(zone.GuardedContentPool); found {
		return tier
	}
	if tier, found := tierFromContentPools(zone.UnguardedContentPool); found {
		return tier
	}
	layout := strings.ToLower(zone.Layout)
	switch {
	case strings.Contains(layout, "sides"):
		return preview.TierBronze
	case strings.Contains(layout, "treasure"):
		return preview.TierSilver
	case strings.Contains(layout, "center"):
		return preview.TierGold
	}
	name := strings.ToLower(zone.Name)
	switch {
	case strings.Contains(name, "low") || strings.Contains(name, "side"):
		return preview.TierBronze
	case strings.Contains(name, "med") || strings.Contains(name, "treasure"):
		return preview.TierSilver
	case strings.Contains(name, "high") || strings.Contains(name, "center") || strings.Contains(name, "core"):
		return preview.TierGold
	}
	return preview.TierBronze
}

// isPlatinumZone reports whether the zone carries the Highest-quality profile:
// tier-5 content pools combined with the rich treasure resources pool.
func isPlatinumZone(zone entities.Zone) bool {
	if !poolsContainMarker(zone.ResourcesContentPool, "treasure_zone_rich") {
		return false
	}
	return poolsContainMarker(zone.GuardedContentPool, "_t5_") ||
		poolsContainMarker(zone.UnguardedContentPool, "_t5_")
}

// poolsContainMarker reports whether any pool SID contains the marker.
func poolsContainMarker(pools []string, marker string) bool {
	for _, pool := range pools {
		if strings.Contains(strings.ToLower(pool), marker) {
			return true
		}
	}
	return false
}

// tierFromContentPools scans pool SIDs for tier markers ("_t1_".."_t5_") and
// returns the highest preview tier found: t4/t5 → gold, t3 → silver, t2 →
// bronze, t1 → plastic. The boolean reports whether any marker was present.
func tierFromContentPools(pools []string) (preview.ZoneTier, bool) {
	best := preview.TierPlastic
	found := false
	for _, pool := range pools {
		lowered := strings.ToLower(pool)
		var tier preview.ZoneTier
		switch {
		case strings.Contains(lowered, "_t5_") || strings.Contains(lowered, "_t4_"):
			tier = preview.TierGold
		case strings.Contains(lowered, "_t3_"):
			tier = preview.TierSilver
		case strings.Contains(lowered, "_t2_"):
			tier = preview.TierBronze
		case strings.Contains(lowered, "_t1_"):
			tier = preview.TierPlastic
		default:
			continue
		}
		found = true
		if tier > best {
			best = tier
		}
	}
	return best, found
}
