package preview_service

import (
	"strings"

	"github.com/Tariomka/hommoe_custom_templates/internal/entities"
)

// ExtractZoneLetter returns the trailing letter portion of a zone name like
// "Spawn-A" → "A" or "Neutral-C" → "C". Plain names (e.g. "Hub") pass through.
func ExtractZoneLetter(zoneName string) string {
	if after, ok := strings.CutPrefix(zoneName, "Spawn-"); ok {
		return after
	}

	if after, ok := strings.CutPrefix(zoneName, "Neutral-"); ok {
		return after
	}

	return zoneName
}

// ClassifyZoneTier guesses a neutral zone's tier from its content pools,
// layout name, and zone name (in order of reliability).
func ClassifyZoneTier(zone entities.Zone) int {
	if strings.HasPrefix(zone.Name, "Spawn-") {
		return 0
	}
	// Most reliable for templates generated by this tool: the guarded content
	// pool names embed the encounter tier (t2/t3/t4/t5). High-tier zones share
	// the "treasure" layout with medium-tier ones, so layout alone cannot
	// distinguish them.
	if tier := tierFromContentPools(zone.GuardedContentPool); tier > 0 {
		return tier
	}
	if tier := tierFromContentPools(zone.UnguardedContentPool); tier > 0 {
		return tier
	}
	layout := strings.ToLower(zone.Layout)
	switch {
	case strings.Contains(layout, "sides"):
		return 1
	case strings.Contains(layout, "treasure"):
		return 2
	case strings.Contains(layout, "center"):
		return 3
	}
	name := strings.ToLower(zone.Name)
	switch {
	case strings.Contains(name, "low") || strings.Contains(name, "side"):
		return 1
	case strings.Contains(name, "med") || strings.Contains(name, "treasure"):
		return 2
	case strings.Contains(name, "high") || strings.Contains(name, "center") || strings.Contains(name, "core"):
		return 3
	}
	return 1
}

// tierFromContentPools scans pool SIDs for tier markers ("_t2_".."_t5_") and
// returns the highest tier found mapped to preview tiers: t4/t5 → 3 (gold),
// t3 → 2 (silver), t2 → 1 (bronze). Returns 0 if no marker is present.
func tierFromContentPools(pools []string) int {
	best := 0
	for _, pool := range pools {
		lowered := strings.ToLower(pool)
		var tier int
		switch {
		case strings.Contains(lowered, "_t5_") || strings.Contains(lowered, "_t4_"):
			tier = 3
		case strings.Contains(lowered, "_t3_"):
			tier = 2
		case strings.Contains(lowered, "_t2_"):
			tier = 1
		}
		if tier > best {
			best = tier
		}
	}
	return best
}
