// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package composition

import (
	"github.com/Tariomka/hommoe_custom_templates/internal/handlers"
	"github.com/Tariomka/hommoe_custom_templates/internal/handlers/handler_interfaces"
	"github.com/Tariomka/hommoe_custom_templates/internal/mappers"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/config"
	"github.com/Tariomka/hommoe_custom_templates/internal/repositories"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/bonuses"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/connection_editor"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/content_rules"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/editor"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/file_service"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/file_system"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/pickers"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/preview_service"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator/generation_tuning"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator/providers"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator/providers/topology/base"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/zone_content"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/zones"
	"github.com/Tariomka/hommoe_custom_templates/internal/validators"
)

// Injectors from wire.go:

func InitializeGuiHandler() handler_interfaces.IGuiHandler {
	generatorConfig := config.NewGeneratorConfig()
	iZoneLabelProvider := zones.NewZoneLabelProvider()
	iGenerationTuningFactory := generation_tuning.NewGenerationTuningFactory()
	iContentLimitProvider := providers.NewContentLimitProvider()
	iZoneClassifier := zones.NewZoneClassifier()
	iCastleFactory := zones.NewCastleFactory()
	iRoadFactory := zones.NewRoadFactory()
	iZoneFactory := zones.NewZoneFactory(iCastleFactory, iRoadFactory)
	iZoneEditorService := connection_editor.NewZoneEditorService(iCastleFactory, iRoadFactory, iZoneFactory)
	iMandatoryContentProvider := providers.NewMandatoryContentProvider(iZoneClassifier, iZoneEditorService)
	iGameRulesProvider := providers.NewGameRulesProvider()
	iGladiatorArenaProvider := providers.NewGladiatorArenaProvider(iZoneClassifier)
	iTopologyConnectionService := base.NewTopologyConnectionService(iZoneLabelProvider)
	iTopologyServiceLookup := provideTopologyServices(iZoneFactory, iRoadFactory, iZoneLabelProvider, iTopologyConnectionService)
	iTopologyProvider := providers.NewTopologyProvider(iTopologyServiceLookup)
	iZoneLayoutProvider := providers.NewZoneLayoutProvider()
	iTemplateGenerator := template_generator.NewTemplateGenerator(generatorConfig, iZoneLabelProvider, iGenerationTuningFactory, iContentLimitProvider, iMandatoryContentProvider, iGameRulesProvider, iGladiatorArenaProvider, iTopologyProvider, iZoneLayoutProvider)
	iContentRuleService := content_rules.NewContentRuleService()
	iMandatoryContentItemMapper := mappers.NewMandatoryContentItemMapper(iContentRuleService)
	iGeneratorConfigMapper := mappers.NewConfigMapper(iMandatoryContentItemMapper)
	iConnectionEditorService := connection_editor.NewConnectionEditorService(iZoneClassifier)
	iManualReapplyService := connection_editor.NewManualReapplyService(iZoneEditorService, iCastleFactory, iZoneClassifier, iGenerationTuningFactory)
	iEditorStateEntityMapper := mappers.NewEditorStateEntityMapper()
	iFileRepository := repositories.NewEditorStateRepository(iEditorStateEntityMapper)
	repositoriesIFileRepository := repositories.NewTemplateRepository()
	iFileRepository2 := repositories.NewPreviewRepository()
	iFileService := file_service.NewFileService(iFileRepository, repositoriesIFileRepository, iFileRepository2)
	iPreviewLayoutService := preview_service.NewPreviewLayoutService()
	iPreviewGeneratorService := providePreviewGenerator(iPreviewLayoutService)
	iEditorStateValidator := validators.NewEditorStateValidator()
	iStateHandler := handlers.NewStateHandler(iFileService, iEditorStateValidator)
	iTemplateHandler := handlers.NewTemplateHandler(iTemplateGenerator, iGeneratorConfigMapper, iMandatoryContentProvider, iConnectionEditorService, iZoneEditorService, iManualReapplyService, iFileService, iPreviewGeneratorService, iStateHandler)
	iPreviewHandler := handlers.NewPreviewHandler(iPreviewLayoutService)
	iContentRuleHandler := handlers.NewContentRuleHandler(iContentRuleService)
	iZoneContentEditorService := zone_content.NewZoneContentEditorService()
	iZoneContentHandler := handlers.NewZoneContentHandler(iContentRuleHandler, iZoneContentEditorService)
	iZoneEditorGeometryService := connection_editor.NewZoneEditorGeometryService(iPreviewLayoutService)
	iZoneEditorHandler := handlers.NewZoneEditorHandler(iGeneratorConfigMapper, iZoneClassifier, iConnectionEditorService, iZoneEditorService, iZoneEditorGeometryService, iGenerationTuningFactory)
	iBonusEntryService := bonuses.NewBonusEntryService()
	iBonusHandler := handlers.NewBonusHandler(iBonusEntryService)
	iPickerEntryService := pickers.NewPickerEntryService()
	iPickerHandler := handlers.NewPickerHandler(iPickerEntryService)
	iGuiHandler := handlers.NewGuiHandler(iTemplateHandler, iStateHandler, iPreviewHandler, iZoneContentHandler, iZoneEditorHandler, iBonusHandler, iPickerHandler)
	return iGuiHandler
}

func InitializeFileSystemHandler() handler_interfaces.IFileSystemHandler {
	iDirectoryBrowserService := file_system.NewDirectoryBrowserService()
	iPathResolutionService := file_system.NewPathResolutionService()
	iFileSystemHandler := handlers.NewFileSystemHandler(iDirectoryBrowserService, iPathResolutionService)
	return iFileSystemHandler
}

func InitializeRegenerationHandler() handler_interfaces.IRegenerationHandler {
	iRegenerationDecisionService := editor.NewRegenerationDecisionService()
	iRegenerationHandler := handlers.NewRegenerationHandler(iRegenerationDecisionService)
	return iRegenerationHandler
}
