// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package composition

import (
	"github.com/Tariomka/hommoe_custom_templates/internal/handlers"
	"github.com/Tariomka/hommoe_custom_templates/internal/handlers/handler_interfaces"
	"github.com/Tariomka/hommoe_custom_templates/internal/mappers"
	"github.com/Tariomka/hommoe_custom_templates/internal/models/config"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/connection_editor"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/content_rules"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/file_service"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/preview_service"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator/generation_tuning"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/template_generator/providers"
	"github.com/Tariomka/hommoe_custom_templates/internal/services/zones"
	"github.com/Tariomka/hommoe_custom_templates/internal/validators"
)

// Injectors from wire.go:

func InitializeGuiHandler() handler_interfaces.IGuiHandler {
	generatorConfig := config.NewGeneratorConfig()
	zoneLabelProvider := zones.NewZoneLabelProvider()
	generationTuningFactory := generation_tuning.NewGenerationTuningFactory()
	contentLimitProvider := providers.NewContentLimitProvider()
	zoneClassifier := zones.NewZoneClassifier()
	castleFactory := zones.NewCastleFactory()
	roadFactory := zones.NewRoadFactory()
	zoneFactory := zones.NewZoneFactory(castleFactory, roadFactory)
	zoneEditorService := connection_editor.NewZoneEditorService(castleFactory, roadFactory, zoneFactory)
	mandatoryContentProvider := providers.NewMandatoryContentProvider(zoneClassifier, zoneEditorService)
	gameRulesProvider := providers.NewGameRulesProvider()
	topologyProvider := providers.NewTopologyProvider(zoneFactory, roadFactory)
	zoneLayoutProvider := providers.NewZoneLayoutProvider()
	templateGenerator := template_generator.NewTemplateGenerator(generatorConfig, zoneLabelProvider, generationTuningFactory, contentLimitProvider, mandatoryContentProvider, gameRulesProvider, topologyProvider, zoneLayoutProvider)
	generatorConfigMapper := mappers.NewConfigMapper()
	connectionEditorService := connection_editor.NewConnectionEditorService(zoneClassifier)
	manualReapplyService := connection_editor.NewManualReapplyService(zoneEditorService, zoneClassifier, generationTuningFactory)
	fileService := file_service.NewFileService()
	previewLayoutService := preview_service.NewPreviewLayoutService()
	previewGeneratorService := providePreviewGenerator(previewLayoutService)
	editorStateValidator := validators.NewEditorStateValidator()
	iStateHandler := handlers.NewStateHandler(fileService, editorStateValidator)
	iTemplateHandler := handlers.NewTemplateHandler(templateGenerator, generatorConfigMapper, mandatoryContentProvider, connectionEditorService, zoneEditorService, manualReapplyService, fileService, previewGeneratorService, iStateHandler)
	iPreviewHandler := handlers.NewPreviewHandler(previewLayoutService)
	contentRuleService := content_rules.NewContentRuleService()
	iContentRuleHandler := handlers.NewContentRuleHandler(contentRuleService)
	iZoneEditorHandler := handlers.NewZoneEditorHandler(generatorConfigMapper, zoneClassifier, connectionEditorService, zoneEditorService, generationTuningFactory)
	iGuiHandler := handlers.NewGuiHandler(iTemplateHandler, iStateHandler, iPreviewHandler, iContentRuleHandler, iZoneEditorHandler)
	return iGuiHandler
}
